--  Oceana X 
--  loader.luau
-- version 1.0.0

repeat task.wait() until game:IsLoaded()

local pi = game.PlaceId

if pi == 121765167512457 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/alessandro-arsv/Oceana-X-/refs/heads/main/bbasketball.luau"))()
end

if pi == 126509999114328 or pi == 113463598817292 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/alessandro-arsv/Oceana-X-/refs/heads/main/99%20Nights%20in%20the%20forest.luau"))()
end